import = [".config/alacritty/gruvbox.toml"]
live_config_reload = true

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Alt"
